(function(){var e=true,f=false,h=window.g={},i=navigator.userAgent.toLowerCase();i.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/);var j=/webkit/.test(i),k=/opera/.test(i),l=/msie/.test(i)&&!/opera/.test(i),m=f,o=f,p=[];function q(){if(!o&&(o=e,p)){for(var a=0;a<p.length;a++)p[a].call(window,[]);p=[]}}function r(){var a=q,c=window.onload;window.onload=typeof window.onload!="function"?a:function(){c&&c();a()}}
function s(){if(!m){m=e;document.addEventListener&&!k&&document.addEventListener("DOMContentLoaded",q,f);l&&window==top&&function(){if(!o){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}q()}}();k&&document.addEventListener("DOMContentLoaded",function(){if(!o){for(var a=0;a<document.styleSheets.length;a++)if(document.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}q()}},f);if(j){var a;(function(){if(!o)if(document.readyState!="loaded"&&document.readyState!=
"complete")setTimeout(arguments.callee,0);else{if(a===void 0){for(var c=document.getElementsByTagName("link"),b=0;b<c.length;b++)c[b].getAttribute("rel")=="stylesheet"&&a++;a+=document.getElementsByTagName("style").length}document.styleSheets.length!=a?setTimeout(arguments.callee,0):q()}})()}r()}}h.ready=function(a){s();o?a.call(window,[]):p.push(function(){return a.call(window,[])})};var t=document,u,v="wumii-comment",w="wurl",y="wtitle",z;
z=typeof wumiiCommentDebugServer!="undefined"?wumiiCommentDebugServer:"http://app.wumii.com";var A=f;if(!l&&(typeof wumiiEnableCustomPos=="undefined"||!wumiiEnableCustomPos||document.getElementById("wumiiDisplayDiv")))try{B(),A=e}catch(C){}h.ready(function(){A||(B(),A=e)});
function B(){for(var a=document.getElementsByTagName("div"),c=[],b=0;b<a.length;b++)a[b].className==v&&c.push(a[b]);if(c.length==0){a=document.createElement("div");a.className=v;c.push(a);b=t.getElementById("wumiiComments");if(!b)return;var d=b.getAttribute("src");if(d&&d.indexOf("pf=Z-Blog")!=-1||typeof wumiiParams!="undefined"&&wumiiParams.indexOf("pf=Z-Blog")!=-1)return;b.parentNode.insertBefore(a,b)}u=D(c);u.length==1?(c=u[0],E(c.c(),c.b())):(F(),G())}
function D(a){function c(a){function b(a,d){for(var c=a.a.getElementsByTagName("input"),n=0;n<c.length;n++)if(c[n].getAttribute("name")==d)return c[n].getAttribute("value");return null}this.a=a;this.e=this.d=f;this.h=function(){return this.a};this.j=function(){return this.d};this.f=function(){this.d=e};this.i=function(){return this.e};this.c=function(){var a=b(this,w);/^\//.test(a)&&typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix?a=wumiiSitePrefix+a:/^http/.test(a)||(a="");!a&&typeof wumiiPermaLink!=
"undefined"&&wumiiPermaLink&&(a=wumiiPermaLink);return!a?(this.e=e,location.href):a};this.b=function(){var a=b(this,y);!a&&typeof wumiiTitle!="undefined"&&(a=wumiiTitle);return a?a:document.title}}for(var b=[],d=0;d<a.length;d++)b[d]=new c(a[d]);return b}
function E(a,c){var b=z+"/ext/cw/comments?url=",d=a;/\#\S*/.test(d)&&(d=d.replace(/\#\S*/,""));b=b+encodeURIComponent(d)+"&title="+encodeURIComponent(c);typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix&&(b+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix));d=document.createElement("script");d.type="text/javascript";d.src=b;document.getElementsByTagName("head")[0].appendChild(d)}
function F(){for(var a=0;a<u.length;a++){var c=u[a],b;if(c.d)b=f;else{b=window.innerHeight||document.documentElement.clientHeight;for(var d=c.a,x=0;d!=null;)x+=d.offsetTop,d=d.offsetParent;d=x-(window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0);b=d>=-400&&d<=800+b}b&&(c.f(),E(c.c(),c.b()))}}
function G(){if(window.addEventListener)window.addEventListener("scroll",function(){F()},f),window.addEventListener("resize",function(){F()},f);else if(window.attachEvent)window.attachEvent("onscroll",function(){F()}),window.attachEvent("onresize",function(){F()});else if(document.getElementById)window.onload=function(){for(var a=0;a<u.length;a++)wumiiDiv.f(),E(wumiiDiv.c(),wumiiDiv.b())}};})();

